apiVersion: v1
kind: Namespace
metadata:
  name: ps2alerts
---
apiVersion: v1
kind: Service
metadata:
  name: ps2alerts-assets
  namespace: ps2alerts
spec:
  selector:
    app: ps2alerts-assets
  ports:
      - protocol: TCP
        port: 80
        targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps2alerts-assets
  namespace: ps2alerts
  labels:
    app: ps2alerts-assets
spec:
  replicas: {{ replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ps2alerts-assets
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ps2alerts-assets
        version: {{ version }}
    spec:
      containers:
        - name: application
          image: maelstromeous/applications:ps2alerts-assets-{{ version }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "5m"
              memory: "32Mi"
            limits:
              cpu: "10m"
              memory: "32Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ps2alerts-assets
  namespace: ps2alerts
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "{{ hostname }}"
      secretName: ps2alerts-assets-tls
  rules:
      - host: "{{ hostname }}"
        http:
          paths:
            - pathType: Prefix
              path: "/"
              backend:
                service:
                  name: ps2alerts-assets
                  port:
                    number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ps2alerts-assets
  namespace: ps2alerts
spec:
  secretName: ps2alerts-assets-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: {{ hostname }}
  dnsNames:
    - {{ hostname }}
