---
name: Build & Deploy
on:
  push:
    branches: [master]
jobs:
  build-docker-images:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: provisioning/Dockerfile
          platforms: linux/amd64
          push: true
          tags: maelstromeous/applications:ps2alerts-assets-${{ github.sha }}

  deploy-to-k8s:
    needs: build-docker-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Inject the templates with the correct variables. {{ version }} refers to the Git SHA and is what changes the container version.
      - name: Update the K8s applicaiton resource file
        run: |
          -e 's|{{ version }}|${{ github.sha }}|' \
          -e 's|{{ replicas }}|3|' \
          -e 's|{{ hostname }}|assets.ps2alerts.com|' \
          provisioning/k8s.yml

      # Apply the common resources, telling k8s to change the container version to the new one.
      - uses: actions-hub/kubectl@master
        name: Apply common resources
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f provisioning/k8s.yml

      # Outputs the rollout status and returns a 0 signal (thus completing the workflow) once it's rolled out.
      - uses: actions-hub/kubectl@master
        name: Wait for deployment to finish
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deployment/ps2alerts-assets -n ps2alerts
